"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$username\
$hostname\
$container\
$directory\
$custom\
$docker_context\
$dotnet\
$helm\
$java\
$nodejs\
$python\
$kubernetes\
$terraform\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = ";"
error_symbol = "!!"

[username]
style_user = "bold green"
format = '[$user]($style)'

[directory]
style = "bold blue"

[hostname]
format = ' on [$hostname](dimmed) '
trim_at = '' # disable trimming

[container]
disabled = false

[git_status]
format = '([\($ahead_behind\)]($style) )'
diverged = "⇣$behind_count ⇡$ahead_count"
ahead = "⇡$count"
behind = "⇣$count"
style = "bold purple"

[nodejs]
symbol = "nodejs "
version_format = "v${major}"

[python]
symbol = "python "

[kubernetes]
format = 'on [($cluster in )$namespace](blue) '
disabled = false
contexts = []

[custom.jj_change_id]
command = "jj log -r@ -l1 --ignore-working-copy --no-graph -T 'self.change_id().shortest()'"
style = "purple"
when = "jj status --quiet"

[custom.jj_change_state]
command = '''
jj log -r@ -l1 --ignore-working-copy --no-graph --color always  -T '
  separate(" ",
    if(empty, "empty"),
    if(conflict, "conflict"),
    if(divergent, "divergent"),
    if(hidden, "hidden"),
  )
'
'''
when = "jj status --quiet"

[custom.jj_state]
description = "Displays the current state of the jj changes."
when = "jj status --quiet"
style = "bold cyan"
command = '''
jj log -r@ -l1 --no-graph -T "" --stat | tail -n1 | sd "(\d+) files? changed, (\d+) insertions?\(\+\), (\d+) deletions?\(-\)" ' ${1}m ${2}+ ${3}-' | sd " 0." ""
'''

[custom.jj_branch]
description = "Displays the current jj branch."
when = "jj status --quiet"
style = "dimmed"
command = "jj log -r@ -l1 --no-graph -T 'self.branches()'"
