"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$username\
$hostname\
$container\
$directory\
$git_branch\
$git_status\
$git_commit\
$git_state\
$git_metrics\
$docker_context\
$dotnet\
$helm\
$java\
$nodejs\
$python\
$kubernetes\
$terraform\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = ";"
error_symbol = "!!"

[username]
style_user = "bold green"
format = '[$user]($style)'

[directory]
style = "bold blue"

[hostname]
format = ' on [$hostname](dimmed) '
trim_at = '' # disable trimming

[container]
disabled = false

[git_status]
format = '([\($ahead_behind\)]($style) )'
diverged = "⇣$behind_count ⇡$ahead_count"
ahead = "⇡$count"
behind = "⇣$count"
style = "bold purple"

[nodejs]
symbol = "nodejs "
version_format = "v${major}"

[python]
symbol = "python "

[kubernetes]
format = 'on [($cluster in )$namespace](blue) '
disabled = false
contexts = []
