"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$username\
$hostname\
$container\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$docker_context\
$dotnet\
$helm\
$java\
$nodejs\
$python\
$terraform\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = ";"
error_symbol = "!!"

[username]
style_user = "bold green"

[directory]
style = "bold blue"

[time]
disabled = false
style = "dimmed white"
format = '[ $time ]($style) '

[git_status]
disabled = true

[dotnet]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

