[language-server.ruby-lsp]
command = "ruby-lsp"
config = { diagnostics = true, formatting = true }

[[language]]
name = "markdown"
text-width = 100

# Required hotfix for taplo's "this document has been excluded" warning.
# https://github.com/tamasfe/taplo/issues/320#issuecomment-2576801631
[[language]]
name = "toml"
roots = ["."]

[[language]]
name = "ruby"
language-servers = [ "ruby-lsp" ]
auto-format=true

[[language]]
name = "go"
auto-format = true
language-servers = [ "gopls", "golangci-lint-lsp" ]

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--output.json.path", "stdout", "--show-stats=false", "--issues-exit-code=1"]

