use-grammars = { only = ["jjdescription"] }

[[language]]
name = "jjdescription"
scope = "jj.description"
file-types = [{ glob = "*.jjdescription" }]
comment-token = "JJ:"
indent = { tab-width = 2, unit = "  " }
rulers = [51, 73]
text-width = 72

[[grammar]]
name = "jjdescription"
source = { git = "https://github.com/kareigu/tree-sitter-jjdescription", rev = "d09205b52b5a0165b588a793e366c1116468d86f" }

[[language]]
name = "markdown"
text-width = 100

# Required hotfix for taplo's "this document has been excluded" warning.
# https://github.com/tamasfe/taplo/issues/320#issuecomment-2576801631
[[language]]
name = "toml"
roots = ["."]
