[[language]]
name = "markdown"
text-width = 100

# Required hotfix for taplo's "this document has been excluded" warning.
# https://github.com/tamasfe/taplo/issues/320#issuecomment-2576801631
[[language]]
name = "toml"
roots = ["."]
