[settings]
experimental = true

# Do not care about .python-version and such.
idiomatic_version_file_enable_tools = []

# Paranoid mode to make sure everything is running over HTTPS and needs my
# explicit approval.
paranoid = true

[tools]
"aqua:codeberg.org/mergiraf/mergiraf" = "latest"
bat = "latest"
chezmoi = "latest"
cosign = "latest"
delta = "latest"
difftastic = "latest"
direnv = "latest"
eza = "latest"
fd = "latest"
flux2 = "latest"
fzf = "latest"
golangci-lint = "latest"
helix = "latest"
jj = "latest"
kubectl = "latest"
ripgrep = "latest"
sd = "latest"
shfmt = "latest"
taplo = "latest"
usage = "latest"
watchexec = "latest"

[hooks]
# Automatically install tools when entering a project:
# https://mise.jdx.dev/tips-and-tricks.html#auto-install-when-entering-a-project
enter = "mise i -q"
