name: ci

on:
  push:
  pull_request:

jobs:
  clone-and-install-devcontainers:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v2
      - run: ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'

  clone-and-install-server:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - name: "Install dependencies"
        run: apt-get update && apt-get install -yy wget curl sudo
      - uses: actions/checkout@v2
      - name: "chezmoi init and apply"
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- -b .local/bin/ init --promptBool "Target is server=true" --apply --source .
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
